---
- name: Install Docker Compose on target server
  hosts: all
  become: yes

  tasks:
    - name: Download Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Check docker-compose version
      command: docker-compose --version
      register: docker_compose_version

    - name: Show docker-compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"

